creating new clean patio repo

diff --git a/.github/workflows/tox-pytest.yml b/.github/workflows/tox-pytest.yml
--- a/.github/workflows/tox-pytest.yml
+++ b/.github/workflows/tox-pytest.yml
@@ -1,53 +1,53 @@
-name: tox-pytest
-
-on: [push, pull_request]
-
-jobs:
-  ci-test:
-    name: ci-test (${{ matrix.python-version }}, ${{ matrix.os }})
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: ["ubuntu-latest", "windows-latest"]
-        python-version: ["3.12", "3.13"]
-      fail-fast: false
-    steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 2
-      - name: Install uv
-        uses: astral-sh/setup-uv@v6
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Install dependencies
-        run: uv tool install tox --with tox-uv
-      - name: Test with tox
-        run: tox
-
-      - name: Coveralls
-        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
-        uses: coverallsapp/github-action@master
-        with:
-          github-token: ${{ secrets.GITHUB_TOKEN }}
-          path-to-lcov: ./coverage.info
-
-  finish:
-    needs: ci-test
-    runs-on: ubuntu-latest
-    steps:
-      - name: Coveralls Finished
-        uses: coverallsapp/github-action@master
-        with:
-          github-token: ${{ secrets.github_token }}
-          parallel-finished: true
-
-  collector:
-    needs: [ci-test]
-    if: always()
-    runs-on: ubuntu-latest
-    steps:
-      - name: check for failures
-        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
-        run: echo job failed && exit 1
+#name: tox-pytest
+#
+#on: [push, pull_request]
+#
+#jobs:
+#  ci-test:
+#    name: ci-test (${{ matrix.python-version }}, ${{ matrix.os }})
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      matrix:
+#        os: ["ubuntu-latest", "windows-latest"]
+#        python-version: ["3.12", "3.13"]
+#      fail-fast: false
+#    steps:
+#      - uses: actions/checkout@v4
+#        with:
+#          fetch-depth: 2
+#      - name: Install uv
+#        uses: astral-sh/setup-uv@v6
+#      - name: Set up Python ${{ matrix.python-version }}
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#      - name: Install dependencies
+#        run: uv tool install tox --with tox-uv
+#      - name: Test with tox
+#        run: tox
+#
+#      - name: Coveralls
+#        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
+#        uses: coverallsapp/github-action@master
+#        with:
+#          github-token: ${{ secrets.GITHUB_TOKEN }}
+#          path-to-lcov: ./coverage.info
+#
+#  finish:
+#    needs: ci-test
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: Coveralls Finished
+#        uses: coverallsapp/github-action@master
+#        with:
+#          github-token: ${{ secrets.github_token }}
+#          parallel-finished: true
+#
+#  collector:
+#    needs: [ci-test]
+#    if: always()
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: check for failures
+#        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+#        run: echo job failed && exit 1
